/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voy.govoyage.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import voy.govoyage.dao.AdminDAO;
import voy.govoyage.entities.Admin;
import java.awt.event.KeyEvent;

/**
 *
 * @author Cherni Mohamed
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        nomt = new javax.swing.JTextField();
        prenomt = new javax.swing.JTextField();
        telt = new javax.swing.JTextField();
        mailt = new javax.swing.JTextField();
        logt = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        passt = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        lvalid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nom.setText("Nom");

        prenom.setText("prenom");

        tel.setText("Tel");

        mail.setText("Mail");

        log.setText("Login");

        pass.setText("Password");

        nomt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtActionPerformed(evt);
            }
        });
        nomt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomtKeyTyped(evt);
            }
        });

        prenomt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prenomtKeyTyped(evt);
            }
        });

        telt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teltKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teltKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teltKeyTyped(evt);
            }
        });

        mailt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailtFocusLost(evt);
            }
        });
        mailt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailtActionPerformed(evt);
            }
        });
        mailt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailtKeyTyped(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        exit.setText("Return");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(prenom)
                                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomt)
                            .addComponent(prenomt)
                            .addComponent(telt)
                            .addComponent(mailt)
                            .addComponent(logt)
                            .addComponent(passt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(exit))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

new AdminDAO().add(new Admin(nomt.getText(),prenomt.getText(),mailt.getText(),Integer.parseInt(telt.getText()),logt.getText(),passt.getText()));
        nomt.setText(null);
        prenomt.setText(null);
        mailt.setText(null);
        telt.setText(null);
        logt.setText(null);
        passt.setText(null);
    }//GEN-LAST:event_addActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new TableAdmin().setVisible(true);
        this.hide();
    }//GEN-LAST:event_exitActionPerformed

    private void nomtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomtKeyPressed
   
    }//GEN-LAST:event_nomtKeyPressed

    private void nomtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomtKeyTyped
           
         if(!(Character.isLetter(evt.getKeyChar()) || evt.getKeyChar()==KeyEvent.VK_BACK_SPACE )){
                 evt.consume();
                 nomt.setBackground(Color.pink);
             }else{
                 nomt.setBackground(Color.white);
             }
         
         
    }//GEN-LAST:event_nomtKeyTyped

    private void teltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teltKeyTyped
       if(!(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)){
                 evt.consume();
                 telt.setBackground(Color.pink);
             }else{
                 telt.setBackground(Color.white);
                 if(telt.getText().length()!=7){
                    telt.setBackground(Color.pink); 
                     if(telt.getText().length()>7){
                    evt.consume();
                     }
                 }
             }
       
    }//GEN-LAST:event_teltKeyTyped

    private void prenomtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomtKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()) || evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)){
                 evt.consume();
                 prenomt.setBackground(Color.pink);
             }else{
                 prenomt.setBackground(Color.white);
             }
       
        
    }//GEN-LAST:event_prenomtKeyTyped

    private void mailtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailtKeyTyped
        if(!(mailt.getText().indexOf("@")>0&&mailt.getText().indexOf("@")<mailt.getText().indexOf(".")&&mailt.getText().indexOf(".")<mailt.getText().length())){
                 lvalid.setText("invalid address");
                 lvalid.setForeground(Color.red);
             }else{
                 lvalid.setText("address accepted");
                 lvalid.setForeground(Color.green);
             }
       
    }//GEN-LAST:event_mailtKeyTyped

    private void mailtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailtActionPerformed

    private void teltKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teltKeyPressed
        
    }//GEN-LAST:event_teltKeyPressed

    private void teltKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teltKeyReleased
        if(telt.getText().length()==8){
            telt.setBackground(Color.white);
        }
    }//GEN-LAST:event_teltKeyReleased

    private void nomtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomtKeyReleased
        nomt.setBackground(Color.white);
    }//GEN-LAST:event_nomtKeyReleased

    private void prenomtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomtKeyReleased
        prenomt.setBackground(Color.white);
    }//GEN-LAST:event_prenomtKeyReleased

    private void mailtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailtFocusLost
        lvalid.setText(null);
    }//GEN-LAST:event_mailtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton exit;
    private javax.swing.JLabel log;
    protected javax.swing.JTextField logt;
    private javax.swing.JLabel lvalid;
    private javax.swing.JLabel mail;
    protected javax.swing.JTextField mailt;
    private javax.swing.JLabel nom;
    protected javax.swing.JTextField nomt;
    private javax.swing.JLabel pass;
    protected javax.swing.JPasswordField passt;
    private javax.swing.JLabel prenom;
    protected javax.swing.JTextField prenomt;
    private javax.swing.JLabel tel;
    protected javax.swing.JTextField telt;
    // End of variables declaration//GEN-END:variables
}
