/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voy.govoyage.gui;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import voy.govoyage.dao.ReservationMDAO;
import voy.govoyage.entities.ReservationM;
import voy.govoyage.util.AffichageReserveM;
import voy.govoyage.gui.ModifierReservationM;
import voy.govoyage.util.AffichagerechercherReservationM;
/**
 *
 * @author Administrateur
 */
public class AffichageReservMClient extends javax.swing.JFrame {

    /**
     * Creates new form AffichageReservMClient
     */
    public AffichageReservMClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        supprimerMC = new javax.swing.JButton();
        modifierMC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rechercheMclient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        annulero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new AffichageReserveM());
        jScrollPane1.setViewportView(jTable1);

        supprimerMC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        supprimerMC.setText("Supprimer");
        supprimerMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerMCActionPerformed(evt);
            }
        });

        modifierMC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifierMC.setText("Modifier");
        modifierMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierMCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Recherche :");

        rechercheMclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheMclientActionPerformed(evt);
            }
        });
        rechercheMclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercheMclientKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("Mes Réservations");

        annulero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        annulero.setText("Retour");
        annulero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuleroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(rechercheMclient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(annulero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifierMC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(supprimerMC, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheMclient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(annulero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(supprimerMC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modifierMC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerMCActionPerformed
        new ReservationMDAO().delete(new ReservationM(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString())));
        jTable1.setModel(new AffichageReserveM());
        JOptionPane.showMessageDialog(this, "suppression effectuée  ");
    }//GEN-LAST:event_supprimerMCActionPerformed

    private void rechercheMclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheMclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheMclientActionPerformed

    private void modifierMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierMCActionPerformed

//       ModifierReservationM rp=new ModifierReservationM();
//        rp.idres.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
//     
//       
//      
//       //rp.tfville.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
//        //(String) jTable1.getValueAt(jTable1.getSelectedRow(), 2)
////        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
////        try {
////            Date datee = format.parse((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
////            rp.dateRR.setDate(datee);
////        } catch (ParseException ex) {
////            Logger.getLogger(TableSejour.class.getName()).log(Level.SEVERE, null, ex);
////        }
////   
//     rp.nb.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
//       
//       
//        
//        rp.setVisible(true);
//       
//          rp.show();
//       this.hide();

ModifierReservationM ua = new ModifierReservationM();
        ua.idres.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        //(String) jTable1.getValueAt(jTable1.getSelectedRow(), 2)
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date datee = format.parse((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
            ua.dateRR.setDate(datee);
        } catch (ParseException ex) {
            Logger.getLogger(AffichageReservMClient.class.getName()).log(Level.SEVERE, null, ex);
        }
   
      ua.nb.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
//        ua.tfid.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        //ua.tfid.setEditable(false);
        //ua.tfid.setEnabled(false);
       
     
       
        
        ua.setVisible(true);
        this.hide();
    }//GEN-LAST:event_modifierMCActionPerformed

    private void annuleroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuleroActionPerformed
        JOptionPane confirmation = new JOptionPane();
        int i=JOptionPane.showConfirmDialog(null, "voulez vous vraiment quitter?",
            "Veuillez confirmer votre choix",
            JOptionPane.YES_NO_OPTION);
        if(i==0){
            this.hide();
            AffichReservationM g=new AffichReservationM();
            g.show();     
    }//GEN-LAST:event_annuleroActionPerformed
    }
    private void rechercheMclientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheMclientKeyReleased
       jTable1.setModel(new AffichagerechercherReservationM(rechercheMclient.getText()));
    }//GEN-LAST:event_rechercheMclientKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageReservMClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageReservMClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageReservMClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageReservMClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichageReservMClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifierMC;
    protected javax.swing.JTextField rechercheMclient;
    private javax.swing.JButton supprimerMC;
    // End of variables declaration//GEN-END:variables
}
