/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voy.govoyage.gui;

import javax.swing.JOptionPane;
import voy.govoyage.dao.AdminDAO;
import voy.govoyage.dao.HotelDAO;
import voy.govoyage.entities.Admin;
import voy.govoyage.entities.Hotel;
import voy.govoyage.util.AffichageRechercheAdmin;
import voy.govoyage.util.AffichageRechercheHotel;
import voy.govoyage.util.affichageTableAdmin;
import voy.govoyage.util.affichageTableHotel;

/**
 *
 * @author user
 */
public class ajouthotel extends javax.swing.JFrame {

    /**
     * Creates new form ajouthotel
     */
    public ajouthotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonajout = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        recherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nomh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paysh = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nombreh = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionh = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        localisationh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        villeh = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        capaciteh = new javax.swing.JTextField();
        ajouth = new javax.swing.JButton();
        validerb = new javax.swing.JButton();
        telephoneh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTable1.setModel(new affichageTableHotel());
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rechercheMouseExited(evt);
            }
        });
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });
        recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercheKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout buttonajoutLayout = new javax.swing.GroupLayout(buttonajout);
        buttonajout.setLayout(buttonajoutLayout);
        buttonajoutLayout.setHorizontalGroup(
            buttonajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonajoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(buttonajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonajoutLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                    .addGroup(buttonajoutLayout.createSequentialGroup()
                        .addGroup(buttonajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonajoutLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jButton1)
                                .addGap(61, 61, 61)
                                .addComponent(jButton2))
                            .addGroup(buttonajoutLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        buttonajoutLayout.setVerticalGroup(
            buttonajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonajoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buttonajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(buttonajoutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nom Hotel:");

        jLabel3.setText("Pays:");

        paysh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunis", "Canada", "France", "italia" }));

        jLabel2.setText("Nombres d'etoiles:");

        nombreh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        nombreh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrehActionPerformed(evt);
            }
        });

        jLabel4.setText("Description :");

        descriptionh.setColumns(20);
        descriptionh.setRows(5);
        jScrollPane1.setViewportView(descriptionh);

        jLabel5.setText("Localisation :");

        localisationh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localisationhActionPerformed(evt);
            }
        });

        jLabel6.setText("Ville :");

        villeh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bizerte", "sousse", "sfax", "jerba" }));

        jLabel7.setText("Capacité :");

        capaciteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacitehActionPerformed(evt);
            }
        });

        ajouth.setText("Ajouter");
        ajouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouthActionPerformed(evt);
            }
        });

        validerb.setText("Valider");
        validerb.setVisible(false);
        validerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerbActionPerformed(evt);
            }
        });

        telephoneh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephonehActionPerformed(evt);
            }
        });

        jLabel8.setText("Telephone :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paysh, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)
                            .addComponent(telephoneh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capaciteh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(villeh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(localisationh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(nombreh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomh)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(validerb, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ajouth, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(buttonajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paysh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreh)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localisationh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(villeh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capaciteh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouth)
                    .addComponent(validerb))
                .addContainerGap())
            .addComponent(buttonajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localisationhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localisationhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localisationhActionPerformed

    private void capacitehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacitehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacitehActionPerformed

    private void ajouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouthActionPerformed
 Hotel  hotel=new Hotel();
        hotel.setNom(nomh.getText());
        hotel.setNombre_e(Integer.parseInt ((String) nombreh.getSelectedItem()));
        hotel.setVille((String) villeh.getSelectedItem());
        hotel.setLocalisation(localisationh.getText());
         hotel.setPays((String) paysh.getSelectedItem());
        hotel.setCapacite(Integer.parseInt(capaciteh.getText()));
        hotel.setDescription(descriptionh.getText());
       hotel.setTelephone(Integer.parseInt ((String) telephoneh.getText()));
      
        new HotelDAO().add(hotel);
        
        nomh.setText(null);
        nombreh.setSelectedItem(null);
        villeh.setSelectedItem(null);
        localisationh.setText(null);
        paysh.setSelectedItem(null);
        capaciteh.setText(null);
        descriptionh.setText(null);
        
        
        
        jTable1.setModel(new affichageTableHotel());
        //JOptionPane.showMessageDialog(rootPane, "ajouté avec succés");
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouthActionPerformed

    private void nombrehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrehActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new HotelDAO().delete(new Hotel(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString())));
        jTable1.setModel(new affichageTableHotel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ajouth.setVisible(false);
        validerb.setVisible(true);
        
        nomh.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        paysh.setSelectedItem((String) jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        nombreh.setSelectedItem((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        descriptionh.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 7));
        localisationh.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
        capaciteh.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
         villeh.setSelectedItem((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
       telephoneh.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void validerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerbActionPerformed
           
           
           Hotel  hotel=new Hotel();
           hotel.setId((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        hotel.setNom(nomh.getText());
        hotel.setNombre_e(Integer.parseInt ((String) nombreh.getSelectedItem()));
        hotel.setVille((String) villeh.getSelectedItem());
        hotel.setLocalisation(localisationh.getText());
         hotel.setPays((String) paysh.getSelectedItem());
        hotel.setCapacite(Integer.parseInt(capaciteh.getText()));
        hotel.setDescription(descriptionh.getText());
          hotel.setTelephone(Integer.parseInt ((String) telephoneh.getText()));
       
      
        new HotelDAO().update(hotel);
        jTable1.setModel(new affichageTableHotel());
        validerb.setVisible(false);
           ajouth.setVisible(true);
           nomh.setText(null);
        nombreh.setSelectedItem(null);
        villeh.setSelectedItem(null);
        localisationh.setText(null);
        paysh.setSelectedItem(null);
        capaciteh.setText(null);
        descriptionh.setText(null);
    }//GEN-LAST:event_validerbActionPerformed

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheActionPerformed

    private void telephonehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephonehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephonehActionPerformed

    private void rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheKeyReleased
       jTable1.setModel(new AffichageRechercheHotel(recherche.getText()));
    }//GEN-LAST:event_rechercheKeyReleased

    private void rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheMouseClicked

    private void rechercheMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouthotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouthotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouthotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouthotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ajouthotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouth;
    private javax.swing.JPanel buttonajout;
    private javax.swing.JTextField capaciteh;
    private javax.swing.JTextArea descriptionh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField localisationh;
    private javax.swing.JComboBox nombreh;
    private javax.swing.JTextField nomh;
    private javax.swing.JComboBox paysh;
    private javax.swing.JTextField recherche;
    private javax.swing.JTextField telephoneh;
    private javax.swing.JButton validerb;
    private javax.swing.JComboBox villeh;
    // End of variables declaration//GEN-END:variables
}
